### PR TITLE
revert package.json and utils.js #882

### PR DESCRIPTION
**Pull request by long76**
plus some unification with [scroll-into-view-if-needed](https://github.com/scroll-into-view/scroll-into-view-if-needed)

### CODE REVIEW

**Comment by long76** [comment]
@stipsan sorry again and please make release

**Review by stipsan — APPROVED** [review]
That's all right, why didn't it work?

**Comment by long76** [comment]
> That's all right, why didn't it work?

it's crash on webpack and i have mistake in my project, thank you

**Comment by stipsan** [comment]
Oki, it happens @long76 I appreciate you quickly resolving it 😄

**Pull request merged**
